services:
  - type: web
    name: research-paper-backend
    env: python
    rootDirectory: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
